oc_plateform_homepage:
    path:     /{page}
    defaults:
        _controller: OCPlateformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

oc_plateform_view:
    path: /advert/{id}
    defaults:
          _controller: OCPlateformBundle:Advert:view
    requirements:
          id: \d+

oc_plateform_add:
    path: /add
    defaults: { _controller: OCPlateformBundle:Advert:add }

oc_plateform_edit:
    path: /edit/{id}
    defaults: { _controller: OCPlateformBundle:Advert:edit }
    requirements:
        id: \d+

oc_plateform_delete:
    path: /delete/{id}
    defaults: { _controller: OCPlateformBundle:Advert:delete }
    requirements:
         id: \d+
